CREATE TABLE USERS(
id
INT AUTO_INCREMENT PRIMARY KEY,
login_id
VARCHAR(100) NOT NULL,
login_pass
VARCHAR(100) NOT NULL,
type INT,
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE TEACHERS(
id
INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
name
VARCHAR(100) NOT NULL,
grade INT,
class_number INT,
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE STUDENTS(
id
INT AUTO_INCREMENT PRIMARY KEY,
users_id INT,
name
VARCHAR(100) NOT NULL,
grade INT,
class_number INT,
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE PARENTS(
id
INT AUTO_INCREMENT PRIMARY KEY,
student_id INT,
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE ITEMS(
id
INT AUTO_INCREMENT PRIMARY KEY,
item_name VARCHAR(100),
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE ITEM_LISTS(
id
INT AUTO_INCREMENT PRIMARY KEY,
date DATE,
grade INT,
class_number INT,
item_id INT,
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE ITEM_CHECK(
id
INT AUTO_INCREMENT PRIMARY KEY,
student_id INT,
date DATE,
item_id INT,
is_checked BOOLEAN,
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE HW(
id
INT AUTO_INCREMENT PRIMARY KEY,
hw_name  VARCHAR(100),
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE HW_LISTS(
id
INT AUTO_INCREMENT PRIMARY KEY,
date DATE,
hw_range VARCHAR(100),
grade INT,
class_number INT,
homework_id INT,
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE HW_CHECK(
id
INT AUTO_INCREMENT PRIMARY KEY,
student_id INT,
date DATE,
hw_range VARCHAR(100),
homework_id INT,
is_checked BOOLEAN,
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE STAMPS(
id
INT AUTO_INCREMENT PRIMARY KEY,
stamp_name VARCHAR(100),
stamp_url VARCHAR(100),
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE REACTIONS(
id
INT AUTO_INCREMENT PRIMARY KEY,
reaction_name VARCHAR(100),
reaction_url VARCHAR(100),
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE STAMP_LOG(
id
INT AUTO_INCREMENT PRIMARY KEY,
student_id INT,
stamp_id INT,
text VARCHAR(100),
reaction_id INT,
is_read BOOLEAN,
created_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP
DEFAULT CURRENT_TIMESTAMP
);